### ISSUE TITLE
Assistance - Usage

### ISSUE THREAD

**Issue by ClientIco** [Anth0rx/reversing-docker#5]
Hi Anth0rx,

Just curious, I was looking for reverse engineering docker images --> How to reverse Engineering a docker image.

I end up finding your repo and realized this is a docker images with reverse engineering tools installed. 

Do you maybe have some usage examples. Or can you maybe included a few examples of how you can reverse engineer something with this docker images ?

**Comment by Anth0rx** [comment]
Hey @ClientIco, nice you dropped by. Actually this image is quite old and hasn't been updated in a while. The container created with this image is able to mount local directories as volumes into a container. Then you can use the tools provided by the container to work with the files you want to analyze.

Let's say you have a few images to reverse-engineer in your `~/Images` folder. Then you'd do a 
`sudo docker run --rm -it -v ~/Images:/workdir anthorx/reversing-docker` to mount this folder and run the container.

But I recommend to build the Image yourself, since the provided version at Docker Hub is 3 years old.

**Comment by ClientIco** [comment]
Thanks Anth0rx, much appreciated! :)
